# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET {{host}}/api/v1/get/cases/1/comments/

###
POST https://d.semalt.com/api/v1/create/cases/1/comments/
Cookie: id=1;hash=fd614d64a1896ccb7b6c9bbf11bbea3b
Content-Type: application/json

{
  "comment": "Comment Text",
  "parent": 0
}

###